# Generated by Django 2.2.2 on 2019-12-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='van_no',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_Department',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_Student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_Teacher',
            field=models.BooleanField(default=False),
        ),
    ]
